# Generated by Django 2.0.7 on 2018-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='order',
        ),
        migrations.RemoveField(
            model_name='check',
            name='waiter',
        ),
        migrations.AlterField(
            model_name='servicepersentage',
            name='persentage',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
