# Generated by Django 2.0.7 on 2018-07-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='service_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.ServicePersentage'),
        ),
    ]
