# Generated by Django 2.0.7 on 2018-07-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_check_service_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='service_fee',
            new_name='persentage',
        ),
    ]
